const fs = require('fs');

// Additional questions for chapters 2-21 (5 per chapter)
const additionalQuestions = {
  2: [
    { id: 'q2_6', question: 'What does Number(true) return?', questionKa: 'რას აბრუნებს Number(true)?', options: ['0', '1', 'NaN', '"true"'], optionsKa: ['0', '1', 'NaN', '"true"'], correctIndex: 1, explanation: 'Number(true) returns 1. Boolean true converts to 1, false to 0.', explanationKa: 'Number(true) აბრუნებს 1-ს. Boolean true 1-ად, false 0-ად კონვერტირდება.' },
    { id: 'q2_7', question: 'What does the ?? (nullish coalescing) operator do?', questionKa: 'რას აკეთებს ?? (nullish coalescing) ოპერატორი?', options: ['Returns left if falsy', 'Returns right if left is null or undefined', 'Compares two values', 'Negates a boolean'], optionsKa: ['მარცხენას აბრუნებს თუ falsy-ა', 'მარჯვენას აბრუნებს თუ მარცხენა null ან undefined-ია', 'ორ მნიშვნელობას ადარებს', 'ბულიანს უარყოფს'], correctIndex: 1, explanation: 'The ?? operator returns the right operand only when the left is null or undefined, unlike || which triggers on any falsy value.', explanationKa: '?? ოპერატორი მარჯვენა ოპერანდს მხოლოდ მაშინ აბრუნებს, როცა მარცხენა null ან undefined-ია.' },
    { id: 'q2_8', question: 'What happens if no case matches in a switch and there is no default?', questionKa: 'რა ხდება თუ switch-ში არცერთი case არ ემთხვევა და default არ არის?', options: ['An error is thrown', 'Nothing happens, execution continues', 'It returns undefined', 'The first case runs'], optionsKa: ['შეცდომა ისვრის', 'არაფერი ხდება, შესრულება გრძელდება', 'undefined-ს აბრუნებს', 'პირველი case სრულდება'], correctIndex: 1, explanation: 'If no case matches and there is no default clause, the switch block is simply skipped.', explanationKa: 'თუ არცერთი case არ ემთხვევა და default არ არის, switch ბლოკი უბრალოდ გამოიტოვება.' },
    { id: 'q2_9', question: 'Which operator has higher precedence: && or ||?', questionKa: 'რომელ ოპერატორს აქვს უფრო მაღალი პრიორიტეტი: && თუ ||?', options: ['|| has higher precedence', '&& has higher precedence', 'They have equal precedence', 'It depends on the context'], optionsKa: ['||-ს აქვს მეტი პრიორიტეტი', '&&-ს აქვს მეტი პრიორიტეტი', 'თანაბარი პრიორიტეტი აქვთ', 'კონტექსტზეა დამოკიდებული'], correctIndex: 1, explanation: 'Logical AND (&&) has higher precedence than logical OR (||).', explanationKa: 'ლოგიკურ AND-ს (&&) უფრო მაღალი პრიორიტეტი აქვს ვიდრე ლოგიკურ OR-ს (||).' },
    { id: 'q2_10', question: 'What is short-circuit evaluation?', questionKa: 'რა არის short-circuit შეფასება?', options: ['Evaluating all operands always', 'Stopping evaluation as soon as result is determined', 'A type of loop', 'Converting types automatically'], optionsKa: ['ყველა ოპერანდის ყოველთვის შეფასება', 'შეფასების შეწყვეტა შედეგის დადგენისთანავე', 'ციკლის ტიპი', 'ტიპების ავტომატური კონვერტაცია'], correctIndex: 1, explanation: 'Short-circuit evaluation stops as soon as the result is determined: false && x skips x, true || x skips x.', explanationKa: 'Short-circuit შეფასება ჩერდება შედეგის დადგენისთანავე: false && x - x-ს გამოტოვებს, true || x - x-ს გამოტოვებს.' }
  ],
  3: [
    { id: 'q3_6', question: 'What does Math.abs(-7) return?', questionKa: 'რას აბრუნებს Math.abs(-7)?', options: ['-7', '7', '0', 'NaN'], optionsKa: ['-7', '7', '0', 'NaN'], correctIndex: 1, explanation: 'Math.abs() returns the absolute (positive) value of a number.', explanationKa: 'Math.abs() რიცხვის აბსოლუტურ (დადებით) მნიშვნელობას აბრუნებს.' },
    { id: 'q3_7', question: 'What does "hello".includes("ell") return?', questionKa: 'რას აბრუნებს "hello".includes("ell")?', options: ['true', 'false', '1', '"ell"'], optionsKa: ['true', 'false', '1', '"ell"'], correctIndex: 0, explanation: '"hello".includes("ell") returns true because "ell" is found within "hello".', explanationKa: '"hello".includes("ell") true-ს აბრუნებს, რადგან "ell" "hello"-ში მოიძებნა.' },
    { id: 'q3_8', question: 'What does "JavaScript".slice(0, 4) return?', questionKa: 'რას აბრუნებს "JavaScript".slice(0, 4)?', options: ['"Java"', '"JavaS"', '"Jav"', '"avaS"'], optionsKa: ['"Java"', '"JavaS"', '"Jav"', '"avaS"'], correctIndex: 0, explanation: 'slice(0, 4) extracts characters from index 0 to 3 (4 is exclusive), giving "Java".', explanationKa: 'slice(0, 4) ინდექს 0-დან 3-მდე სიმბოლოებს ამოიღებს (4 ექსკლუზიურია), რაც "Java"-ს იძლევა.' },
    { id: 'q3_9', question: 'How do you generate a random integer from 1 to 10?', questionKa: 'როგორ გენერირებთ შემთხვევით მთელ რიცხვს 1-დან 10-მდე?', options: ['Math.random() * 10', 'Math.floor(Math.random() * 10) + 1', 'Math.ceil(Math.random() * 10) + 1', 'Math.round(Math.random()) * 10'], optionsKa: ['Math.random() * 10', 'Math.floor(Math.random() * 10) + 1', 'Math.ceil(Math.random() * 10) + 1', 'Math.round(Math.random()) * 10'], correctIndex: 1, explanation: 'Math.floor(Math.random() * 10) + 1 gives a random integer from 1 to 10 inclusive.', explanationKa: 'Math.floor(Math.random() * 10) + 1 შემთხვევით მთელ რიცხვს 1-დან 10-ის ჩათვლით იძლევა.' },
    { id: 'q3_10', question: 'What does "Hello World".split(" ") return?', questionKa: 'რას აბრუნებს "Hello World".split(" ")?', options: ['"Hello World"', '["Hello", "World"]', '["H","e","l","l","o"," ","W","o","r","l","d"]', '["Hello World"]'], optionsKa: ['"Hello World"', '["Hello", "World"]', '["H","e","l","l","o"," ","W","o","r","l","d"]', '["Hello World"]'], correctIndex: 1, explanation: 'split(" ") splits the string at each space, creating an array of words.', explanationKa: 'split(" ") სტრინგს ყოველ სფეისზე ყოფს, სიტყვების მასივს ქმნის.' }
  ],
  4: [
    { id: 'q4_6', question: 'What will a for loop "for(let i=0; i<3; i++)" execute how many times?', questionKa: 'for ციკლი "for(let i=0; i<3; i++)" რამდენჯერ შესრულდება?', options: ['2', '3', '4', 'Infinite'], optionsKa: ['2', '3', '4', 'უსასრულოდ'], correctIndex: 1, explanation: 'The loop runs for i=0, i=1, i=2 (three iterations), then i becomes 3 and the condition i<3 is false.', explanationKa: 'ციკლი სრულდება i=0, i=1, i=2 (სამი იტერაცია), შემდეგ i ხდება 3 და i<3 პირობა false-ია.' },
    { id: 'q4_7', question: 'What does the continue statement do inside a loop?', questionKa: 'რას აკეთებს continue ოპერატორი ციკლში?', options: ['Exits the loop', 'Skips to the next iteration', 'Restarts the loop from the beginning', 'Pauses execution'], optionsKa: ['ციკლიდან გამოდის', 'შემდეგ იტერაციაზე გადადის', 'ციკლს თავიდან იწყებს', 'შესრულებას აჩერებს'], correctIndex: 1, explanation: 'continue skips the remaining code in the current iteration and moves to the next one.', explanationKa: 'continue მიმდინარე იტერაციაში დანარჩენ კოდს გამოტოვებს და შემდეგზე გადადის.' },
    { id: 'q4_8', question: 'Which loop guarantees at least one execution of the body?', questionKa: 'რომელი ციკლი უზრუნველყოფს სხეულის ერთხელ მაინც შესრულებას?', options: ['for', 'while', 'do...while', 'for...of'], optionsKa: ['for', 'while', 'do...while', 'for...of'], correctIndex: 2, explanation: 'do...while executes the body first, then checks the condition.', explanationKa: 'do...while ჯერ სხეულს ასრულებს, შემდეგ ამოწმებს პირობას.' },
    { id: 'q4_9', question: 'What causes an infinite loop?', questionKa: 'რა იწვევს უსასრულო ციკლს?', options: ['Using break', 'A condition that never becomes false', 'Using continue', 'Declaring a counter'], optionsKa: ['break-ის გამოყენება', 'პირობა, რომელიც არასოდეს ხდება false', 'continue-ის გამოყენება', 'მრიცხველის გამოცხადება'], correctIndex: 1, explanation: 'An infinite loop occurs when the loop condition always remains true.', explanationKa: 'უსასრულო ციკლი ხდება, როცა ციკლის პირობა ყოველთვის true რჩება.' },
    { id: 'q4_10', question: 'What does for...of iterate over?', questionKa: 'რაზე გადის for...of?', options: ['Object keys', 'Object values only', 'Values of iterable objects (arrays, strings)', 'Class methods'], optionsKa: ['ობიექტის გასაღებებზე', 'მხოლოდ ობიექტის მნიშვნელობებზე', 'იტერირებადი ობიექტების (მასივები, სტრინგები) მნიშვნელობებზე', 'კლასის მეთოდებზე'], correctIndex: 2, explanation: 'for...of iterates over values of iterable objects like arrays, strings, Maps, and Sets.', explanationKa: 'for...of იტერირებადი ობიექტების (მასივები, სტრინგები, Map, Set) მნიშვნელობებზე გადის.' }
  ],
  5: [
    { id: 'q5_6', question: 'What does [1,2,3].includes(2) return?', questionKa: 'რას აბრუნებს [1,2,3].includes(2)?', options: ['1', 'true', 'false', '2'], optionsKa: ['1', 'true', 'false', '2'], correctIndex: 1, explanation: 'includes() returns true if the array contains the specified value.', explanationKa: 'includes() true-ს აბრუნებს თუ მასივი შეიცავს მითითებულ მნიშვნელობას.' },
    { id: 'q5_7', question: 'What does Array.isArray([1,2]) return?', questionKa: 'რას აბრუნებს Array.isArray([1,2])?', options: ['true', 'false', '"array"', '"object"'], optionsKa: ['true', 'false', '"array"', '"object"'], correctIndex: 0, explanation: 'Array.isArray() is the reliable way to check if a value is an array — returns true for arrays.', explanationKa: 'Array.isArray() სანდო გზაა მნიშვნელობის მასივობის შესამოწმებლად — მასივებისთვის true-ს აბრუნებს.' },
    { id: 'q5_8', question: 'What does splice(1, 2) do to [a, b, c, d]?', questionKa: 'რას უკეთებს splice(1, 2) მასივს [a, b, c, d]?', options: ['Removes a and b', 'Removes b and c', 'Adds 2 elements at index 1', 'Returns [a, d]'], optionsKa: ['შლის a-ს და b-ს', 'შლის b-ს და c-ს', 'ინდექს 1-ზე 2 ელემენტს ამატებს', 'აბრუნებს [a, d]'], correctIndex: 1, explanation: 'splice(1, 2) starts at index 1 and removes 2 elements (b and c), leaving [a, d].', explanationKa: 'splice(1, 2) ინდექს 1-დან იწყებს და 2 ელემენტს შლის (b და c), რჩება [a, d].' },
    { id: 'q5_9', question: 'What does [1,2].concat([3,4]) return?', questionKa: 'რას აბრუნებს [1,2].concat([3,4])?', options: ['[1,2,3,4]', '[[1,2],[3,4]]', '[1,2,[3,4]]', 'Error'], optionsKa: ['[1,2,3,4]', '[[1,2],[3,4]]', '[1,2,[3,4]]', 'შეცდომა'], correctIndex: 0, explanation: 'concat() merges arrays into a new flat array without modifying the originals.', explanationKa: 'concat() მასივებს ახალ ბრტყელ მასივში აერთიანებს ორიგინალების შეცვლის გარეშე.' },
    { id: 'q5_10', question: 'What does .length return for an empty array []?', questionKa: 'რას აბრუნებს .length ცარიელი მასივისთვის []?', options: ['undefined', 'null', '0', '-1'], optionsKa: ['undefined', 'null', '0', '-1'], correctIndex: 2, explanation: 'An empty array has a length of 0.', explanationKa: 'ცარიელ მასივს სიგრძე 0 აქვს.' }
  ],
  6: [
    { id: 'q6_6', question: 'What does [[1,2],[3,4]].flat() return?', questionKa: 'რას აბრუნებს [[1,2],[3,4]].flat()?', options: ['[[1,2],[3,4]]', '[1,2,3,4]', '[[1,2,3,4]]', 'Error'], optionsKa: ['[[1,2],[3,4]]', '[1,2,3,4]', '[[1,2,3,4]]', 'შეცდომა'], correctIndex: 1, explanation: 'flat() flattens nested arrays by one level, creating [1,2,3,4].', explanationKa: 'flat() ჩადგმულ მასივებს ერთი დონით ასწორებს, ქმნის [1,2,3,4].' },
    { id: 'q6_7', question: 'How do you access the element 5 in [[1,2],[3,[4,5]]]?', questionKa: 'როგორ მიწვდებით ელემენტ 5-ს [[1,2],[3,[4,5]]]-ში?', options: ['arr[1][1][1]', 'arr[2][1]', 'arr[1][2]', 'arr[1][1]'], optionsKa: ['arr[1][1][1]', 'arr[2][1]', 'arr[1][2]', 'arr[1][1]'], correctIndex: 0, explanation: 'arr[1] is [3,[4,5]], arr[1][1] is [4,5], arr[1][1][1] is 5.', explanationKa: 'arr[1] არის [3,[4,5]], arr[1][1] არის [4,5], arr[1][1][1] არის 5.' },
    { id: 'q6_8', question: 'What does the spread operator do with nested arrays?', questionKa: 'რას აკეთებს spread ოპერატორი ჩადგმულ მასივებთან?', options: ['Deep copies everything', 'Only shallow copies the top level', 'Flattens all levels', 'Converts to object'], optionsKa: ['ყველაფერს ღრმად კოპირებს', 'მხოლოდ ზედა დონეს ზედაპირულად კოპირებს', 'ყველა დონეს ასწორებს', 'ობიექტად გარდაქმნის'], correctIndex: 1, explanation: 'Spread creates a shallow copy — nested arrays still reference the same objects.', explanationKa: 'Spread ზედაპირულ ასლს ქმნის — ჩადგმული მასივები მაინც იმავე ობიექტებზე მიუთითებს.' },
    { id: 'q6_9', question: 'What is flatMap() equivalent to?', questionKa: 'flatMap() რის ექვივალენტია?', options: ['map() then flat()', 'flat() then map()', 'filter() then map()', 'reduce() then flat()'], optionsKa: ['map() შემდეგ flat()', 'flat() შემდეგ map()', 'filter() შემდეგ map()', 'reduce() შემდეგ flat()'], correctIndex: 0, explanation: 'flatMap() is equivalent to calling map() followed by flat(1) in a single step.', explanationKa: 'flatMap() ექვივალენტია map()-ის, შემდეგ flat(1)-ის ერთ ნაბიჯად გამოძახების.' },
    { id: 'q6_10', question: 'What is a matrix in programming?', questionKa: 'რა არის მატრიცა პროგრამირებაში?', options: ['A 1D array', 'A 2D array (array of arrays)', 'A string of numbers', 'An object with arrays'], optionsKa: ['ერთგანზომილებიანი მასივი', 'ორგანზომილებიანი მასივი (მასივების მასივი)', 'რიცხვების სტრინგი', 'მასივებიანი ობიექტი'], correctIndex: 1, explanation: 'A matrix is a 2D array — an array of arrays, forming rows and columns.', explanationKa: 'მატრიცა არის 2D მასივი — მასივების მასივი, რომელიც რიგებსა და სვეტებს ქმნის.' }
  ],
  7: [
    { id: 'q7_6', question: 'What is the difference between parameters and arguments?', questionKa: 'რა განსხვავებაა პარამეტრებსა და არგუმენტებს შორის?', options: ['They are the same thing', 'Parameters are in definition, arguments are actual values passed', 'Arguments are in definition, parameters are passed', 'Parameters are for arrow functions only'], optionsKa: ['ისინი ერთი და იგივეა', 'პარამეტრები განსაზღვრებაშია, არგუმენტები გადაცემული მნიშვნელობებია', 'არგუმენტები განსაზღვრებაშია, პარამეტრები გადაეცემა', 'პარამეტრები მხოლოდ arrow ფუნქციებისთვისაა'], correctIndex: 1, explanation: 'Parameters are variables listed in function definition; arguments are actual values passed when calling.', explanationKa: 'პარამეტრები ფუნქციის განსაზღვრებაში ჩამოთვლილი ცვლადებია; არგუმენტები — გამოძახებისას გადაცემული მნიშვნელობები.' },
    { id: 'q7_7', question: 'What are default parameters?', questionKa: 'რა არის ნაგულისხმევი პარამეტრები?', options: ['Parameters that must always be provided', 'Parameters with preset values used when no argument is passed', 'Parameters that cannot be changed', 'The first parameter in a function'], optionsKa: ['პარამეტრები, რომლებიც ყოველთვის უნდა მიეცეს', 'წინასწარ დაყენებული მნიშვნელობის პარამეტრები, როცა არგუმენტი არ გადაეცემა', 'პარამეტრები, რომელთა შეცვლა არ შეიძლება', 'ფუნქციის პირველი პარამეტრი'], correctIndex: 1, explanation: 'Default parameters provide fallback values: function greet(name = "World") uses "World" if no name is passed.', explanationKa: 'ნაგულისხმევი პარამეტრები სათადარიგო მნიშვნელობებს იძლევა: function greet(name = "World") "World"-ს იყენებს თუ არ გადაეცა.' },
    { id: 'q7_8', question: 'Are function declarations hoisted?', questionKa: 'ჰოისტ ხდება თუ არა ფუნქციის გამოცხადებები?', options: ['No, never', 'Yes, both declarations and expressions', 'Yes, but only function declarations, not expressions', 'Only with let'], optionsKa: ['არა, არასოდეს', 'დიახ, გამოცხადებებიც და გამოსახულებებიც', 'დიახ, მაგრამ მხოლოდ ფუნქციის გამოცხადებები, არა გამოსახულებები', 'მხოლოდ let-ით'], correctIndex: 2, explanation: 'Function declarations are hoisted (can be called before declaration), but function expressions are not.', explanationKa: 'ფუნქციის გამოცხადებები ჰოისტ ხდება (გამოძახება შეიძლება გამოცხადებამდე), მაგრამ გამოსახულებები — არა.' },
    { id: 'q7_9', question: 'What does a void function return?', questionKa: 'რას აბრუნებს void ფუნქცია?', options: ['null', '0', 'undefined', 'false'], optionsKa: ['null', '0', 'undefined', 'false'], correctIndex: 2, explanation: 'A function without a return statement (void) implicitly returns undefined.', explanationKa: 'ფუნქცია return ოპერატორის გარეშე (void) იმპლიციტურად undefined-ს აბრუნებს.' },
    { id: 'q7_10', question: 'What is function scope?', questionKa: 'რა არის ფუნქციის სკოუპი?', options: ['Variables accessible everywhere', 'Variables declared inside a function are only accessible within it', 'Variables shared between functions', 'The function name'], optionsKa: ['ყველგან ხელმისაწვდომი ცვლადები', 'ფუნქციის შიგნით გამოცხადებული ცვლადები მხოლოდ მის შიგნით არის ხელმისაწვდომი', 'ფუნქციებს შორის გაზიარებული ცვლადები', 'ფუნქციის სახელი'], correctIndex: 1, explanation: 'Variables declared inside a function are locally scoped — they cannot be accessed outside the function.', explanationKa: 'ფუნქციის შიგნით გამოცხადებული ცვლადები ლოკალური სკოუპისაა — ფუნქციის გარეთ მიუწვდომელია.' }
  ],
  8: [
    { id: 'q8_6', question: 'What does arrow function NOT have that regular functions do?', questionKa: 'რა არ აქვს arrow ფუნქციას, რაც ჩვეულებრივ ფუნქციას აქვს?', options: ['Parameters', 'Return value', 'Its own "this" binding', 'Access to variables'], optionsKa: ['პარამეტრები', 'დაბრუნების მნიშვნელობა', 'საკუთარი "this" ბაინდინგი', 'ცვლადებზე წვდომა'], correctIndex: 2, explanation: 'Arrow functions do not have their own "this" — they inherit it from the enclosing scope.', explanationKa: 'Arrow ფუნქციებს საკუთარი "this" არ აქვთ — მშობელი სკოუპიდან იღებენ.' },
    { id: 'q8_7', question: 'What does [1,2,3].find(x => x > 1) return?', questionKa: 'რას აბრუნებს [1,2,3].find(x => x > 1)?', options: ['[2,3]', '2', '1', 'true'], optionsKa: ['[2,3]', '2', '1', 'true'], correctIndex: 1, explanation: 'find() returns the first element that satisfies the condition. 2 is the first number > 1.', explanationKa: 'find() პირველ ელემენტს აბრუნებს, რომელიც პირობას აკმაყოფილებს. 2 პირველი რიცხვია > 1.' },
    { id: 'q8_8', question: 'What does [1,2,3].every(x => x > 0) return?', questionKa: 'რას აბრუნებს [1,2,3].every(x => x > 0)?', options: ['true', 'false', '[1,2,3]', '3'], optionsKa: ['true', 'false', '[1,2,3]', '3'], correctIndex: 0, explanation: 'every() returns true if ALL elements pass the test. All elements are > 0, so it returns true.', explanationKa: 'every() true-ს აბრუნებს თუ ყველა ელემენტი ტესტს გაივლის. ყველა > 0-ია, ამიტომ true.' },
    { id: 'q8_9', question: 'What does [1,2,3].reduce((sum, x) => sum + x, 0) return?', questionKa: 'რას აბრუნებს [1,2,3].reduce((sum, x) => sum + x, 0)?', options: ['[1,2,3]', '0', '6', '3'], optionsKa: ['[1,2,3]', '0', '6', '3'], correctIndex: 2, explanation: 'reduce accumulates: 0+1=1, 1+2=3, 3+3=6. Final result is 6.', explanationKa: 'reduce აგროვებს: 0+1=1, 1+2=3, 3+3=6. საბოლოო შედეგი 6-ია.' },
    { id: 'q8_10', question: 'What is method chaining with array methods?', questionKa: 'რა არის მეთოდების ჯაჭვური გამოძახება მასივის მეთოდებთან?', options: ['Using one method per line', 'Calling multiple methods in sequence: arr.filter().map().reduce()', 'Assigning methods to variables', 'Nesting arrays'], optionsKa: ['ერთი მეთოდი ხაზზე', 'მრავალი მეთოდის თანმიმდევრულად გამოძახება: arr.filter().map().reduce()', 'მეთოდების ცვლადებში მინიჭება', 'მასივების ჩადგმა'], correctIndex: 1, explanation: 'Method chaining calls multiple methods in sequence, each operating on the result of the previous.', explanationKa: 'მეთოდების ჯაჭვი მრავალ მეთოდს თანმიმდევრულად იძახებს, თითოეული წინას შედეგზე მუშაობს.' }
  ],
  9: [
    { id: 'q9_6', question: 'What does Object.values({a:1, b:2}) return?', questionKa: 'რას აბრუნებს Object.values({a:1, b:2})?', options: ['["a","b"]', '[1,2]', '[["a",1],["b",2]]', '{a:1,b:2}'], optionsKa: ['["a","b"]', '[1,2]', '[["a",1],["b",2]]', '{a:1,b:2}'], correctIndex: 1, explanation: 'Object.values() returns an array of the object property values.', explanationKa: 'Object.values() ობიექტის თვისებების მნიშვნელობების მასივს აბრუნებს.' },
    { id: 'q9_7', question: 'What does Object.entries({x:1}) return?', questionKa: 'რას აბრუნებს Object.entries({x:1})?', options: ['["x"]', '[1]', '[["x",1]]', '{x:1}'], optionsKa: ['["x"]', '[1]', '[["x",1]]', '{x:1}'], correctIndex: 2, explanation: 'Object.entries() returns an array of [key, value] pairs.', explanationKa: 'Object.entries() [გასაღებ, მნიშვნელობა] წყვილების მასივს აბრუნებს.' },
    { id: 'q9_8', question: 'When should you use bracket notation obj["key"] instead of dot notation obj.key?', questionKa: 'როდის უნდა გამოიყენოთ ფრჩხილი obj["key"] წერტილის obj.key ნაცვლად?', options: ['Always', 'When the key is stored in a variable', 'When the key is a number', 'Never, they are identical'], optionsKa: ['ყოველთვის', 'როცა გასაღები ცვლადში ინახება', 'როცა გასაღები რიცხვია', 'არასოდეს, ისინი იდენტურია'], correctIndex: 1, explanation: 'Use bracket notation when the property key is dynamic (stored in a variable) or has special characters.', explanationKa: 'ფრჩხილი გამოიყენეთ როცა თვისების გასაღები დინამიურია (ცვლადში ინახება) ან სპეციალური სიმბოლოები აქვს.' },
    { id: 'q9_9', question: 'What does the "this" keyword refer to inside an object method?', questionKa: 'თის (this) საკვანძო სიტყვა რას მიუთითებს ობიექტის მეთოდში?', options: ['The global window', 'The function itself', 'The object the method belongs to', 'undefined'], optionsKa: ['გლობალურ window-ს', 'თავად ფუნქციას', 'ობიექტს, რომელსაც მეთოდი ეკუთვნის', 'undefined-ს'], correctIndex: 2, explanation: 'Inside an object method, "this" refers to the object that owns the method.', explanationKa: 'ობიექტის მეთოდის შიგნით "this" ობიექტზე მიუთითებს, რომელსაც მეთოდი ეკუთვნის.' },
    { id: 'q9_10', question: 'What does Object.freeze() do?', questionKa: 'რას აკეთებს Object.freeze()?', options: ['Deletes all properties', 'Prevents modification of existing properties and adding new ones', 'Makes a deep copy', 'Converts to array'], optionsKa: ['ყველა თვისებას შლის', 'არსებული თვისებების შეცვლას და ახლის დამატებას კრძალავს', 'ღრმა ასლს ქმნის', 'მასივად გარდაქმნის'], correctIndex: 1, explanation: 'Object.freeze() makes an object immutable — you cannot add, remove, or modify properties.', explanationKa: 'Object.freeze() ობიექტს უცვლელს ხდის — თვისებების დამატება, წაშლა ან შეცვლა არ შეიძლება.' }
  ],
  10: [
    { id: 'q10_6', question: 'Why is getMonth() confusing for beginners?', questionKa: 'რატომ აბნევს getMonth() დამწყებებს?', options: ['It returns the month name', 'Months are 0-indexed (Jan=0, Dec=11)', 'It needs a parameter', 'It returns a string'], optionsKa: ['თვის სახელს აბრუნებს', 'თვეები 0-ინდექსირებულია (იანვ=0, დეკ=11)', 'პარამეტრი სჭირდება', 'სტრინგს აბრუნებს'], correctIndex: 1, explanation: 'getMonth() returns 0-11, not 1-12. January is 0, December is 11.', explanationKa: 'getMonth() 0-11-ს აბრუნებს, არა 1-12-ს. იანვარი 0-ია, დეკემბერი 11.' },
    { id: 'q10_7', question: 'How do you stop a setTimeout from executing?', questionKa: 'როგორ აჩერებთ setTimeout-ის შესრულებას?', options: ['clearInterval()', 'clearTimeout()', 'stopTimeout()', 'cancelTimer()'], optionsKa: ['clearInterval()', 'clearTimeout()', 'stopTimeout()', 'cancelTimer()'], correctIndex: 1, explanation: 'clearTimeout(timerId) cancels a timeout that was set with setTimeout().', explanationKa: 'clearTimeout(timerId) setTimeout()-ით დაყენებულ ტაიმაუტს აუქმებს.' },
    { id: 'q10_8', question: 'What does Date.now() return?', questionKa: 'რას აბრუნებს Date.now()?', options: ['Current date string', 'Milliseconds since Jan 1, 1970', 'Current year', 'A Date object'], optionsKa: ['მიმდინარე თარიღის სტრინგი', 'მილიწამები 1970 წლის 1 იანვრიდან', 'მიმდინარე წელი', 'Date ობიექტი'], correctIndex: 1, explanation: 'Date.now() returns the number of milliseconds elapsed since the Unix epoch (Jan 1, 1970).', explanationKa: 'Date.now() Unix epoch-იდან (1970/1/1) გასულ მილიწამთა რაოდენობას აბრუნებს.' },
    { id: 'q10_9', question: 'What is the return value of setInterval()?', questionKa: 'რას აბრუნებს setInterval()?', options: ['undefined', 'A timer ID number', 'A Promise', 'The function result'], optionsKa: ['undefined', 'ტაიმერის ID ნომერს', 'Promise-ს', 'ფუნქციის შედეგს'], correctIndex: 1, explanation: 'setInterval() returns a numeric timer ID that can be used with clearInterval() to stop it.', explanationKa: 'setInterval() რიცხვით ტაიმერის ID-ს აბრუნებს, რომელიც clearInterval()-ით შეჩერებისთვის გამოიყენება.' },
    { id: 'q10_10', question: 'What method converts a Date to a human-readable string?', questionKa: 'რომელი მეთოდი გარდაქმნის Date-ს ადამიანისთვის წაკითხვად სტრინგად?', options: ['toString()', 'parse()', 'valueOf()', 'getTime()'], optionsKa: ['toString()', 'parse()', 'valueOf()', 'getTime()'], correctIndex: 0, explanation: 'toString() converts a Date object to a human-readable string representation.', explanationKa: 'toString() Date ობიექტს ადამიანისთვის წაკითხვად სტრინგად გარდაქმნის.' }
  ],
  11: [
    { id: 'q11_6', question: 'What is the time complexity of Bubble Sort?', questionKa: 'რა არის Bubble Sort-ის დროითი სირთულე?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(1)'], optionsKa: ['O(n)', 'O(n log n)', 'O(n²)', 'O(1)'], correctIndex: 2, explanation: 'Bubble Sort has O(n²) time complexity due to nested loops comparing each pair.', explanationKa: 'Bubble Sort-ს O(n²) დროითი სირთულე აქვს ჩადგმული ციკლების გამო.' },
    { id: 'q11_7', question: 'What does [10,2,1].sort() return?', questionKa: 'რას აბრუნებს [10,2,1].sort()?', options: ['[1,2,10]', '[10,2,1]', '[1,10,2]', '[2,1,10]'], optionsKa: ['[1,2,10]', '[10,2,1]', '[1,10,2]', '[2,1,10]'], correctIndex: 2, explanation: 'sort() converts to strings by default, so "1" < "10" < "2" alphabetically.', explanationKa: 'sort() ნაგულისხმევად სტრინგებად გარდაქმნის, ამიტომ "1" < "10" < "2" ანბანურად.' },
    { id: 'q11_8', question: 'Which sorting method is built into modern JS engines?', questionKa: 'რომელი სორტირების მეთოდი არის ჩაშენებული თანამედროვე JS ძრავებში?', options: ['Bubble Sort', 'Quick Sort', 'Timsort', 'Merge Sort'], optionsKa: ['Bubble Sort', 'Quick Sort', 'Timsort', 'Merge Sort'], correctIndex: 2, explanation: 'Modern JS engines (V8, SpiderMonkey) use Timsort, a hybrid of merge sort and insertion sort.', explanationKa: 'თანამედროვე JS ძრავები (V8, SpiderMonkey) Timsort-ს იყენებენ — merge sort-ისა და insertion sort-ის ჰიბრიდი.' },
    { id: 'q11_9', question: 'Does sort() mutate the original array?', questionKa: 'ცვლის თუ არა sort() ორიგინალ მასივს?', options: ['No, it returns a new array', 'Yes, it modifies in place', 'Only with a comparator', 'Only for numbers'], optionsKa: ['არა, ახალ მასივს აბრუნებს', 'დიახ, ადგილობრივად ცვლის', 'მხოლოდ შემდარებლით', 'მხოლოდ რიცხვებისთვის'], correctIndex: 1, explanation: 'sort() modifies the original array in place. Use toSorted() (ES2023) for a non-mutating version.', explanationKa: 'sort() ორიგინალ მასივს ადგილობრივად ცვლის. toSorted() (ES2023) არამუტაციური ვერსიაა.' },
    { id: 'q11_10', question: 'How do you sort numbers in descending order?', questionKa: 'როგორ ალაგებთ რიცხვებს კლებადობით?', options: ['arr.sort()', 'arr.sort((a,b) => b - a)', 'arr.sort((a,b) => a - b)', 'arr.reverse().sort()'], optionsKa: ['arr.sort()', 'arr.sort((a,b) => b - a)', 'arr.sort((a,b) => a - b)', 'arr.reverse().sort()'], correctIndex: 1, explanation: 'arr.sort((a,b) => b - a) sorts numbers in descending order by reversing the comparison.', explanationKa: 'arr.sort((a,b) => b - a) რიცხვებს კლებადობით ალაგებს შედარების შებრუნებით.' }
  ],
  12: [
    { id: 'q12_6', question: 'What is the difference between textContent and innerHTML?', questionKa: 'რა განსხვავებაა textContent-სა და innerHTML-ს შორის?', options: ['No difference', 'textContent returns only text, innerHTML returns HTML markup too', 'innerHTML is faster', 'textContent can set HTML tags'], optionsKa: ['განსხვავება არ არის', 'textContent მხოლოდ ტექსტს აბრუნებს, innerHTML HTML მარქაფსაც', 'innerHTML უფრო სწრაფია', 'textContent HTML ტეგების დაყენება შეუძლია'], correctIndex: 1, explanation: 'textContent gets/sets only text (strips HTML), while innerHTML preserves HTML tags.', explanationKa: 'textContent მხოლოდ ტექსტს იღებს/აყენებს (HTML-ს შლის), ხოლო innerHTML HTML ტეგებს ინახავს.' },
    { id: 'q12_7', question: 'What does querySelectorAll() return?', questionKa: 'რას აბრუნებს querySelectorAll()?', options: ['A single element', 'An array', 'A NodeList', 'A string'], optionsKa: ['ერთ ელემენტს', 'მასივს', 'NodeList-ს', 'სტრინგს'], correctIndex: 2, explanation: 'querySelectorAll() returns a NodeList of all elements matching the CSS selector.', explanationKa: 'querySelectorAll() CSS სელექტორთან თანხვედრი ყველა ელემენტის NodeList-ს აბრუნებს.' },
    { id: 'q12_8', question: 'What does event.preventDefault() do?', questionKa: 'რას აკეთებს event.preventDefault()?', options: ['Stops event bubbling', 'Prevents the default browser action', 'Removes the event listener', 'Reloads the page'], optionsKa: ['ივენთ ბაბლინგს აჩერებს', 'ბრაუზერის ნაგულისხმევ მოქმედებას კრძალავს', 'ივენთ მსმენელს შლის', 'გვერდს გადატვირთს'], correctIndex: 1, explanation: 'preventDefault() stops the browser default action, like form submission or link navigation.', explanationKa: 'preventDefault() ბრაუზერის ნაგულისხმევ მოქმედებას აჩერებს, მაგ. ფორმის submit-ს ან ბმულზე გადასვლას.' },
    { id: 'q12_9', question: 'Which method adds an element to the DOM?', questionKa: 'რომელი მეთოდი ამატებს ელემენტს DOM-ში?', options: ['createElement()', 'appendChild()', 'querySelector()', 'addEventListener()'], optionsKa: ['createElement()', 'appendChild()', 'querySelector()', 'addEventListener()'], correctIndex: 1, explanation: 'appendChild() adds a child element to a parent node in the DOM.', explanationKa: 'appendChild() მშობელ ნოდს შვილი ელემენტს ამატებს DOM-ში.' },
    { id: 'q12_10', question: 'What does event.target refer to?', questionKa: 'რას მიუთითებს event.target?', options: ['The parent element', 'The element that triggered the event', 'The document', 'The window'], optionsKa: ['მშობელ ელემენტს', 'ელემენტს, რომელმაც ივენთი გამოიწვია', 'დოკუმენტს', 'ფანჯარას'], correctIndex: 1, explanation: 'event.target refers to the actual element that was clicked or triggered the event.', explanationKa: 'event.target მიუთითებს ელემენტზე, რომელზეც მართლა მოხდა დაჭერა ან ივენთის გამოწვევა.' }
  ],
  13: [
    { id: 'q13_6', question: 'What does classList.toggle("active") do if active class already exists?', questionKa: 'რას აკეთებს classList.toggle("active") თუ active კლასი უკვე არსებობს?', options: ['Adds it again', 'Removes it', 'Does nothing', 'Throws error'], optionsKa: ['ხელახლა ამატებს', 'შლის', 'არაფერს აკეთებს', 'შეცდომას ისვრის'], correctIndex: 1, explanation: 'toggle() removes the class if it exists, adds it if it does not.', explanationKa: 'toggle() კლასს შლის თუ არსებობს, ამატებს თუ არ არსებობს.' },
    { id: 'q13_7', question: 'How do you check if an element has a specific class?', questionKa: 'როგორ ამოწმებთ ელემენტს აქვს თუ არა კონკრეტული კლასი?', options: ['element.hasClass("name")', 'element.classList.contains("name")', 'element.className == "name"', 'element.class("name")'], optionsKa: ['element.hasClass("name")', 'element.classList.contains("name")', 'element.className == "name"', 'element.class("name")'], correctIndex: 1, explanation: 'classList.contains("name") returns true if the element has that class.', explanationKa: 'classList.contains("name") true-ს აბრუნებს თუ ელემენტს ეს კლასი აქვს.' },
    { id: 'q13_8', question: 'What is the advantage of classList over className?', questionKa: 'რა უპირატესობა აქვს classList-ს className-ზე?', options: ['classList is faster', 'classList allows adding/removing individual classes without affecting others', 'className cannot read classes', 'classList works only in modern browsers'], optionsKa: ['classList უფრო სწრაფია', 'classList ინდივიდუალური კლასების დამატება/წაშლას იძლევა სხვებზე ზემოქმედების გარეშე', 'className კლასების წაკითხვა არ შეუძლია', 'classList მხოლოდ თანამედროვე ბრაუზერებში მუშაობს'], correctIndex: 1, explanation: 'classList provides methods to manage individual classes without overwriting the entire class string.', explanationKa: 'classList ინდივიდუალური კლასების მართვის მეთოდებს იძლევა მთელი კლასის სტრინგის გადაწერის გარეშე.' },
    { id: 'q13_9', question: 'What does toggle("dark", true) do?', questionKa: 'რას აკეთებს toggle("dark", true)?', options: ['Toggles as normal', 'Forces adding the class', 'Forces removing the class', 'Throws error'], optionsKa: ['ჩვეულებრივად გადართავს', 'იძულებით ამატებს კლასს', 'იძულებით შლის კლასს', 'შეცდომას ისვრის'], correctIndex: 1, explanation: 'The second boolean parameter forces: true always adds, false always removes.', explanationKa: 'მეორე boolean პარამეტრი იძულებით: true ყოველთვის ამატებს, false ყოველთვის შლის.' },
    { id: 'q13_10', question: 'How can you dynamically change a CSS custom property?', questionKa: 'როგორ შეცვლით CSS custom property-ს დინამიურად?', options: ['element.style.setProperty("--color", "red")', 'element.css("--color", "red")', 'element.setStyle("--color", "red")', 'document.setVariable("--color", "red")'], optionsKa: ['element.style.setProperty("--color", "red")', 'element.css("--color", "red")', 'element.setStyle("--color", "red")', 'document.setVariable("--color", "red")'], correctIndex: 0, explanation: 'style.setProperty() can set CSS custom properties (variables) dynamically on elements.', explanationKa: 'style.setProperty() ელემენტებზე CSS custom properties-ს (ცვლადებს) დინამიურად აყენებს.' }
  ],
  14: [
    { id: 'q14_6', question: 'What is event delegation?', questionKa: 'რა არის ივენთ დელეგაცია?', options: ['Attaching events to every element', 'Attaching one event listener to a parent to handle child events', 'Removing all event listeners', 'Using setTimeout with events'], optionsKa: ['ყოველ ელემენტზე ივენთის მიმაგრება', 'ერთი ივენთ მსმენელის მშობელზე მიმაგრება შვილი ელემენტების ივენთების დასამუშავებლად', 'ყველა ივენთ მსმენელის წაშლა', 'setTimeout-ის ივენთებთან გამოყენება'], correctIndex: 1, explanation: 'Event delegation attaches one listener to a parent element, using event.target to identify which child was clicked.', explanationKa: 'ივენთ დელეგაცია ერთ მსმენელს მშობელ ელემენტზე ამაგრებს, event.target-ით ადგენს რომელ შვილზე მოხდა დაჭერა.' },
    { id: 'q14_7', question: 'What does document.createElement("div") do?', questionKa: 'რას აკეთებს document.createElement("div")?', options: ['Selects an existing div', 'Creates a new div element in memory', 'Appends a div to the page', 'Removes a div from the page'], optionsKa: ['არსებულ div-ს ირჩევს', 'ახალ div ელემენტს ქმნის მეხსიერებაში', 'გვერდზე div-ს ამატებს', 'გვერდიდან div-ს შლის'], correctIndex: 1, explanation: 'createElement() creates a new element in memory — it still needs to be appended to the DOM.', explanationKa: 'createElement() ახალ ელემენტს მეხსიერებაში ქმნის — ჯერ კიდევ DOM-ში მიმაგრება სჭირდება.' },
    { id: 'q14_8', question: 'What is requestAnimationFrame used for?', questionKa: 'რისთვის გამოიყენება requestAnimationFrame?', options: ['Making API requests', 'Creating smooth 60fps animations', 'Downloading images', 'Sorting arrays'], optionsKa: ['API მოთხოვნების გაკეთება', 'გლუვი 60fps ანიმაციების შექმნა', 'სურათების ჩამოტვირთვა', 'მასივების სორტირება'], correctIndex: 1, explanation: 'requestAnimationFrame() syncs with the browser refresh rate for smooth, efficient animations.', explanationKa: 'requestAnimationFrame() ბრაუზერის განახლების სიხშირეს სინქრონიზდება გლუვი, ეფექტური ანიმაციებისთვის.' },
    { id: 'q14_9', question: 'What does the dataset property access?', questionKa: 'რაზე აქვს წვდომა dataset თვისებას?', options: ['CSS classes', 'Custom data-* attributes', 'Event listeners', 'Local storage'], optionsKa: ['CSS კლასებზე', 'Custom data-* ატრიბუტებზე', 'ივენთ მსმენელებზე', 'ლოკალურ storage-ზე'], correctIndex: 1, explanation: 'The dataset property provides read/write access to custom data-* attributes on elements.', explanationKa: 'dataset თვისება ელემენტებზე custom data-* ატრიბუტების წაკითხვა/ჩაწერის წვდომას იძლევა.' },
    { id: 'q14_10', question: 'Which SweetAlert2 method shows a confirmation dialog?', questionKa: 'SweetAlert2-ის რომელი მეთოდი აჩვენებს დადასტურების დიალოგს?', options: ['Swal.alert()', 'Swal.fire() with confirmButton', 'Swal.confirm()', 'Swal.show()'], optionsKa: ['Swal.alert()', 'Swal.fire() confirmButton-ით', 'Swal.confirm()', 'Swal.show()'], correctIndex: 1, explanation: 'Swal.fire() with showCancelButton and confirmButtonText options creates a confirmation dialog.', explanationKa: 'Swal.fire() showCancelButton და confirmButtonText ოფციებით დადასტურების დიალოგს ქმნის.' }
  ],
  15: [
    { id: 'q15_6', question: 'Which event fires on every keystroke in an input field?', questionKa: 'რომელი ივენთი ირთვება ყოველ კლავიშზე input ველში?', options: ['click', 'change', 'input', 'submit'], optionsKa: ['click', 'change', 'input', 'submit'], correctIndex: 2, explanation: 'The "input" event fires on every value change, including typing, pasting, and deleting.', explanationKa: '"input" ივენთი ყოველი მნიშვნელობის ცვლილებისას ირთვება — აკრეფა, ჩასმა, წაშლა.' },
    { id: 'q15_7', question: 'What does FileReader.readAsDataURL() produce?', questionKa: 'რას ქმნის FileReader.readAsDataURL()?', options: ['A file path', 'A base64-encoded data URL', 'A Blob', 'A Buffer'], optionsKa: ['ფაილის გზას', 'Base64-კოდირებულ data URL-ს', 'Blob-ს', 'Buffer-ს'], correctIndex: 1, explanation: 'readAsDataURL() produces a base64-encoded data URL that can be used as img src for preview.', explanationKa: 'readAsDataURL() base64-კოდირებულ data URL-ს ქმნის, რომელიც img src-ად შეიძლება გამოიყენოთ.' },
    { id: 'q15_8', question: 'What does the regex flag "g" mean?', questionKa: 'რას ნიშნავს regex-ის "g" ფლაგი?', options: ['Group', 'Global (find all matches)', 'Greedy', 'Generate'], optionsKa: ['ჯგუფი', 'გლობალური (ყველა თანხვედრის პოვნა)', 'ხარბი', 'გენერირება'], correctIndex: 1, explanation: 'The "g" flag makes the regex search for all matches, not just the first one.', explanationKa: '"g" ფლაგი regex-ს ყველა თანხვედრის ძიებას უბრძანებს, არა მხოლოდ პირველის.' },
    { id: 'q15_9', question: 'Which regex method returns true/false?', questionKa: 'Regex-ის რომელი მეთოდი აბრუნებს true/false-ს?', options: ['match()', 'test()', 'replace()', 'search()'], optionsKa: ['match()', 'test()', 'replace()', 'search()'], correctIndex: 1, explanation: 'test() returns true if the pattern matches the string, false otherwise.', explanationKa: 'test() true-ს აბრუნებს თუ შაბლონი სტრინგს ემთხვევა, false-ს — თუ არა.' },
    { id: 'q15_10', question: 'What does /^\\d{3}-\\d{4}$/ validate?', questionKa: 'რას ამოწმებს /^\\d{3}-\\d{4}$/?', options: ['Email address', 'A pattern like 123-4567', 'IP address', 'URL'], optionsKa: ['ელ-ფოსტის მისამართს', 'შაბლონს, როგორიცაა 123-4567', 'IP მისამართს', 'URL-ს'], correctIndex: 1, explanation: 'This regex matches exactly 3 digits, a dash, and 4 digits (like a phone number format).', explanationKa: 'ეს regex ზუსტად 3 ციფრს, ტირეს და 4 ციფრს ემთხვევა (ტელეფონის ფორმატი).' }
  ],
  16: [
    { id: 'q16_6', question: 'What is the correct Content-Type header for sending JSON?', questionKa: 'რა არის სწორი Content-Type header JSON-ის გაგზავნისთვის?', options: ['text/html', 'application/json', 'text/json', 'application/x-json'], optionsKa: ['text/html', 'application/json', 'text/json', 'application/x-json'], correctIndex: 1, explanation: 'application/json is the standard MIME type for JSON data.', explanationKa: 'application/json არის JSON მონაცემების სტანდარტული MIME ტიპი.' },
    { id: 'q16_7', question: 'What HTTP status code means "Not Found"?', questionKa: 'რომელი HTTP სტატუს კოდი ნიშნავს "ვერ მოიძებნა"?', options: ['200', '400', '404', '500'], optionsKa: ['200', '400', '404', '500'], correctIndex: 2, explanation: '404 means the requested resource was not found on the server.', explanationKa: '404 ნიშნავს, რომ მოთხოვნილი რესურსი სერვერზე ვერ მოიძებნა.' },
    { id: 'q16_8', question: 'What does fetch() return?', questionKa: 'რას აბრუნებს fetch()?', options: ['JSON data directly', 'A Promise that resolves to a Response', 'An XMLHttpRequest', 'A string'], optionsKa: ['პირდაპირ JSON მონაცემებს', 'Promise-ს, რომელიც Response-ად გადაიწყვეტება', 'XMLHttpRequest-ს', 'სტრინგს'], correctIndex: 1, explanation: 'fetch() returns a Promise that resolves to a Response object, which you then process with .json().', explanationKa: 'fetch() Promise-ს აბრუნებს, რომელიც Response ობიექტად გადაიწყვეტება, შემდეგ .json()-ით ამუშავებთ.' },
    { id: 'q16_9', question: 'What is CORS?', questionKa: 'რა არის CORS?', options: ['A JavaScript library', 'Cross-Origin Resource Sharing — security mechanism for cross-domain requests', 'A data format', 'A CSS feature'], optionsKa: ['JavaScript ბიბლიოთეკა', 'Cross-Origin Resource Sharing — უსაფრთხოების მექანიზმი cross-domain მოთხოვნებისთვის', 'მონაცემთა ფორმატი', 'CSS ფუნქცია'], correctIndex: 1, explanation: 'CORS is a browser security mechanism that restricts which domains can make requests to your server.', explanationKa: 'CORS ბრაუზერის უსაფრთხოების მექანიზმია, რომელიც ზღუდავს რომელ დომენებს შეუძლიათ სერვერზე მოთხოვნები.' },
    { id: 'q16_10', question: 'How do you send data with a POST request using fetch?', questionKa: 'როგორ აგზავნით მონაცემებს POST მოთხოვნით fetch-ის გამოყენებით?', options: ['fetch(url, data)', 'fetch(url, { method: "POST", body: JSON.stringify(data) })', 'fetch.post(url, data)', 'fetch(url).post(data)'], optionsKa: ['fetch(url, data)', 'fetch(url, { method: "POST", body: JSON.stringify(data) })', 'fetch.post(url, data)', 'fetch(url).post(data)'], correctIndex: 1, explanation: 'fetch() takes a second argument with method, headers, and body for POST requests.', explanationKa: 'fetch() მეორე არგუმენტად method, headers და body-ს იღებს POST მოთხოვნებისთვის.' }
  ],
  17: [
    { id: 'q17_6', question: 'What are the three states of a Promise?', questionKa: 'რა არის Promise-ის სამი მდგომარეობა?', options: ['start, middle, end', 'pending, fulfilled, rejected', 'open, closed, error', 'waiting, done, failed'], optionsKa: ['დასაწყისი, შუალედი, დასასრული', 'pending, fulfilled, rejected', 'ღია, დახურული, შეცდომა', 'მოლოდინი, დასრულებული, ჩავარდნილი'], correctIndex: 1, explanation: 'A Promise is pending initially, then becomes either fulfilled (resolved) or rejected.', explanationKa: 'Promise თავდაპირველად pending-ია, შემდეგ ხდება fulfilled (გადაწყვეტილი) ან rejected (უარყოფილი).' },
    { id: 'q17_7', question: 'What does Promise.all() do?', questionKa: 'რას აკეთებს Promise.all()?', options: ['Runs promises one by one', 'Waits for ALL promises to resolve, or rejects if any fails', 'Returns the fastest promise', 'Cancels all promises'], optionsKa: ['Promise-ებს სათითაოდ აშვებს', 'ყველა Promise-ის გადაწყვეტას ელოდება, ან უარყოფს თუ რომელიმე ჩავარდება', 'ყველაზე სწრაფ Promise-ს აბრუნებს', 'ყველა Promise-ს აუქმებს'], correctIndex: 1, explanation: 'Promise.all() runs promises in parallel and resolves when all complete, or rejects on the first failure.', explanationKa: 'Promise.all() Promise-ებს პარალელურად აშვებს და გადაიწყვეტება ყველას დასრულებისას, ან უარყოფს პირველ ჩავარდნაზე.' },
    { id: 'q17_8', question: 'What does the "await" keyword do?', questionKa: 'რას აკეთებს "await" საკვანძო სიტყვა?', options: ['Creates a new Promise', 'Pauses the async function until the Promise resolves', 'Rejects a Promise', 'Runs code synchronously'], optionsKa: ['ახალ Promise-ს ქმნის', 'ასინქრონულ ფუნქციას აჩერებს Promise-ის გადაწყვეტამდე', 'Promise-ს უარყოფს', 'კოდს სინქრონულად აშვებს'], correctIndex: 1, explanation: 'await pauses the execution of an async function until the Promise settles.', explanationKa: 'await ასინქრონული ფუნქციის შესრულებას აჩერებს Promise-ის დასრულებამდე.' },
    { id: 'q17_9', question: 'Where can you use the await keyword?', questionKa: 'სად შეიძლება await საკვანძო სიტყვის გამოყენება?', options: ['Anywhere', 'Only inside async functions', 'Only in callbacks', 'Only with setTimeout'], optionsKa: ['ყველგან', 'მხოლოდ async ფუნქციების შიგნით', 'მხოლოდ callback-ებში', 'მხოლოდ setTimeout-თან'], correctIndex: 1, explanation: 'await can only be used inside functions declared with the async keyword (or top-level in modules).', explanationKa: 'await მხოლოდ async საკვანძო სიტყვით გამოცხადებულ ფუნქციებში (ან მოდულების ზედა დონეზე) შეიძლება.' },
    { id: 'q17_10', question: 'How do you handle errors with async/await?', questionKa: 'როგორ ამუშავებთ შეცდომებს async/await-ით?', options: ['.catch() only', 'try/catch block', '.then() only', 'No error handling needed'], optionsKa: ['მხოლოდ .catch()', 'try/catch ბლოკით', 'მხოლოდ .then()', 'შეცდომების მართვა არ სჭირდება'], correctIndex: 1, explanation: 'With async/await, wrap your code in try/catch to handle errors cleanly.', explanationKa: 'async/await-ით კოდი try/catch-ში უნდა გახვიოთ შეცდომების სუფთა მართვისთვის.' }
  ],
  18: [
    { id: 'q18_6', question: 'What is the storage limit of localStorage in most browsers?', questionKa: 'რა არის localStorage-ის ლიმიტი ბრაუზერების უმეტესობაში?', options: ['4 KB', '5-10 MB', '100 MB', 'Unlimited'], optionsKa: ['4 KB', '5-10 MB', '100 MB', 'შეუზღუდავი'], correctIndex: 1, explanation: 'localStorage typically allows 5-10 MB per origin in most modern browsers.', explanationKa: 'localStorage ჩვეულებრივ 5-10 MB-ს იძლევა ორიჯინზე თანამედროვე ბრაუზერების უმეტესობაში.' },
    { id: 'q18_7', question: 'How do you store an object in localStorage?', questionKa: 'როგორ ინახავთ ობიექტს localStorage-ში?', options: ['localStorage.setItem("key", obj)', 'localStorage.setItem("key", JSON.stringify(obj))', 'localStorage.setObject("key", obj)', 'localStorage.store(obj)'], optionsKa: ['localStorage.setItem("key", obj)', 'localStorage.setItem("key", JSON.stringify(obj))', 'localStorage.setObject("key", obj)', 'localStorage.store(obj)'], correctIndex: 1, explanation: 'localStorage stores strings only. Use JSON.stringify() to convert objects to strings first.', explanationKa: 'localStorage მხოლოდ სტრინგებს ინახავს. JSON.stringify()-ით ობიექტი ჯერ სტრინგად უნდა გარდაქმნათ.' },
    { id: 'q18_8', question: 'When is sessionStorage cleared?', questionKa: 'როდის იშლება sessionStorage?', options: ['After 24 hours', 'When the browser tab/window is closed', 'Only manually with clear()', 'After 1 hour'], optionsKa: ['24 საათის შემდეგ', 'ბრაუზერის ჩანართის/ფანჯრის დახურვისას', 'მხოლოდ ხელით clear()-ით', '1 საათის შემდეგ'], correctIndex: 1, explanation: 'sessionStorage data is cleared when the tab or window is closed.', explanationKa: 'sessionStorage მონაცემები იშლება ჩანართის ან ფანჯრის დახურვისას.' },
    { id: 'q18_9', question: 'How much data can a cookie store?', questionKa: 'რამდენი მონაცემის შენახვა შეუძლია cookie-ს?', options: ['4 KB', '5 MB', '10 MB', '1 MB'], optionsKa: ['4 KB', '5 MB', '10 MB', '1 MB'], correctIndex: 0, explanation: 'Cookies are limited to about 4 KB per cookie, much less than localStorage.', explanationKa: 'Cookies დაახლოებით 4 KB-ით არის შეზღუდული — ბევრად ნაკლები ვიდრე localStorage.' },
    { id: 'q18_10', question: 'What is the security concern with storing tokens in localStorage?', questionKa: 'რა არის უსაფრთხოების პრობლემა localStorage-ში ტოკენების შენახვისას?', options: ['Data expires too quickly', 'Vulnerable to XSS attacks — any script can read it', 'Too much storage used', 'Cookies are always better'], optionsKa: ['მონაცემები ძალიან სწრაფად იწურება', 'XSS შეტევებისთვის მოწყვლადი — ნებისმიერ სკრიპტს შეუძლია წაკითხვა', 'ძალიან ბევრი storage გამოიყენება', 'Cookies ყოველთვის უკეთესია'], correctIndex: 1, explanation: 'localStorage is accessible by any JavaScript on the page, making it vulnerable to XSS attacks.', explanationKa: 'localStorage გვერდზე ნებისმიერი JavaScript-ისთვის ხელმისაწვდომია, რაც XSS შეტევებისთვის მოწყვლადს ხდის.' }
  ],
  19: [
    { id: 'q19_6', question: 'What does the "static" keyword mean in a class?', questionKa: 'რას ნიშნავს "static" საკვანძო სიტყვა კლასში?', options: ['The method cannot be changed', 'The method belongs to the class, not instances', 'The method runs automatically', 'The method is private'], optionsKa: ['მეთოდის შეცვლა არ შეიძლება', 'მეთოდი კლასს ეკუთვნის, არა ინსტანციებს', 'მეთოდი ავტომატურად სრულდება', 'მეთოდი პრივატულია'], correctIndex: 1, explanation: 'Static methods belong to the class itself and are called as ClassName.method(), not instance.method().', explanationKa: 'Static მეთოდები თავად კლასს ეკუთვნის და ClassName.method()-ით გამოიძახება, არა instance.method()-ით.' },
    { id: 'q19_7', question: 'What is a getter in a class?', questionKa: 'რა არის getter კლასში?', options: ['A regular method', 'A method accessed like a property using get keyword', 'A constructor parameter', 'A private field'], optionsKa: ['ჩვეულებრივი მეთოდი', 'get საკვანძო სიტყვით თვისების მსგავსად ხელმისაწვდომი მეთოდი', 'კონსტრუქტორის პარამეტრი', 'პრივატული ველი'], correctIndex: 1, explanation: 'A getter is defined with get keyword and accessed like a property: obj.name instead of obj.name().', explanationKa: 'Getter get საკვანძო სიტყვით განისაზღვრება და თვისების მსგავსად ხელმისაწვდომია: obj.name, არა obj.name().' },
    { id: 'q19_8', question: 'What does instanceof check?', questionKa: 'რას ამოწმებს instanceof?', options: ['If variable is defined', 'If an object was created by a specific class', 'If two objects are equal', 'If a class exists'], optionsKa: ['ცვლადი განსაზღვრულია თუ არა', 'ობიექტი კონკრეტული კლასის მიერ არის თუ არა შექმნილი', 'ორი ობიექტი ტოლია თუ არა', 'კლასი არსებობს თუ არა'], correctIndex: 1, explanation: 'instanceof checks if an object was created from a specific class (or its parent class).', explanationKa: 'instanceof ამოწმებს ობიექტი კონკრეტული კლასის (ან მისი მშობელი კლასის) მიერ არის თუ არა შექმნილი.' },
    { id: 'q19_9', question: 'What happens if you forget to use "new" when creating a class instance?', questionKa: 'რა ხდება თუ "new"-ს დაივიწყებთ კლასის ინსტანციის შექმნისას?', options: ['It works normally', 'A TypeError is thrown', 'It returns undefined', 'It creates a global object'], optionsKa: ['ნორმალურად მუშაობს', 'TypeError ისვრის', 'undefined-ს აბრუნებს', 'გლობალურ ობიექტს ქმნის'], correctIndex: 1, explanation: 'Classes in JavaScript require the new keyword. Calling a class without new throws a TypeError.', explanationKa: 'JavaScript-ში კლასები new საკვანძო სიტყვას მოითხოვენ. კლასის new-ს გარეშე გამოძახება TypeError-ს ისვრის.' },
    { id: 'q19_10', question: 'What are the four pillars of OOP?', questionKa: 'რა არის OOP-ის ოთხი საყრდენი?', options: ['Variables, Functions, Loops, Arrays', 'Abstraction, Encapsulation, Inheritance, Polymorphism', 'Create, Read, Update, Delete', 'HTML, CSS, JS, DOM'], optionsKa: ['ცვლადები, ფუნქციები, ციკლები, მასივები', 'აბსტრაქცია, ინკაფსულაცია, მემკვიდრეობა, პოლიმორფიზმი', 'შექმნა, წაკითხვა, განახლება, წაშლა', 'HTML, CSS, JS, DOM'], correctIndex: 1, explanation: 'The four pillars of OOP are Abstraction, Encapsulation, Inheritance, and Polymorphism.', explanationKa: 'OOP-ის ოთხი საყრდენია: აბსტრაქცია, ინკაფსულაცია, მემკვიდრეობა და პოლიმორფიზმი.' }
  ],
  20: [
    { id: 'q20_6', question: 'What does super() do in a child class constructor?', questionKa: 'რას აკეთებს super() შვილი კლასის კონსტრუქტორში?', options: ['Creates a new instance', 'Calls the parent class constructor', 'Makes the class static', 'Defines a private field'], optionsKa: ['ახალ ინსტანციას ქმნის', 'მშობელი კლასის კონსტრუქტორს იძახებს', 'კლასს სტატიკურს ხდის', 'პრივატულ ველს განსაზღვრავს'], correctIndex: 1, explanation: 'super() calls the parent class constructor, which must be called before using "this" in a child constructor.', explanationKa: 'super() მშობელი კლასის კონსტრუქტორს იძახებს, რომელიც უნდა გამოიძახოს შვილ კონსტრუქტორში "this"-ის გამოყენებამდე.' },
    { id: 'q20_7', question: 'How do you declare a private field in JavaScript?', questionKa: 'როგორ გამოაცხადებთ პრივატულ ველს JavaScript-ში?', options: ['private name', '_name', '#name', 'protected name'], optionsKa: ['private name', '_name', '#name', 'protected name'], correctIndex: 2, explanation: 'Private fields use the # prefix: #name. They are only accessible within the class body.', explanationKa: 'პრივატული ველები # პრეფიქსს იყენებენ: #name. მხოლოდ კლასის სხეულის შიგნით არის ხელმისაწვდომი.' },
    { id: 'q20_8', question: 'What is method overriding?', questionKa: 'რა არის მეთოდის გადაფარვა?', options: ['Calling a parent method', 'Redefining a parent method in a child class', 'Adding parameters to a method', 'Making a method private'], optionsKa: ['მშობელი მეთოდის გამოძახება', 'მშობელი მეთოდის ხელახალი განსაზღვრა შვილ კლასში', 'მეთოდისთვის პარამეტრების დამატება', 'მეთოდის პრივატულად გადაქცევა'], correctIndex: 1, explanation: 'Method overriding means a child class provides its own implementation of a method inherited from the parent.', explanationKa: 'მეთოდის გადაფარვა ნიშნავს, რომ შვილი კლასი მშობლისგან მემკვიდრეობით მიღებული მეთოდის საკუთარ იმპლემენტაციას იძლევა.' },
    { id: 'q20_9', question: 'Can a child class access parent private fields (#)?', questionKa: 'შეუძლია თუ არა შვილ კლასს მშობლის პრივატულ ველებზე (#) წვდომა?', options: ['Yes, always', 'No, private fields are only accessible in the defining class', 'Yes, with super', 'Only with extends'], optionsKa: ['დიახ, ყოველთვის', 'არა, პრივატული ველები მხოლოდ განმსაზღვრელ კლასში ხელმისაწვდომია', 'დიახ, super-ით', 'მხოლოდ extends-ით'], correctIndex: 1, explanation: 'Private fields (#) cannot be accessed by child classes — they are truly private to the defining class.', explanationKa: 'პრივატული ველები (#) შვილ კლასებისთვის მიუწვდომელია — ისინი ნამდვილად პრივატულია განმსაზღვრელ კლასში.' },
    { id: 'q20_10', question: 'What is the _ prefix convention used for?', questionKa: 'რისთვის გამოიყენება _ პრეფიქსის კონვენცია?', options: ['It makes fields truly private', 'It signals that a field/method is intended for internal use', 'It is required by JavaScript', 'It prevents inheritance'], optionsKa: ['ველებს ნამდვილად პრივატულს ხდის', 'სიგნალიზებს, რომ ველი/მეთოდი შიდა გამოყენებისთვისაა', 'JavaScript მოითხოვს', 'მემკვიდრეობას კრძალავს'], correctIndex: 1, explanation: 'The _ prefix is a convention (not enforced) signaling that a property is intended for internal use only.', explanationKa: '_ პრეფიქსი კონვენციაა (არა იძულებითი), რომელიც სიგნალიზებს რომ თვისება მხოლოდ შიდა გამოყენებისთვისაა.' }
  ],
  21: [
    { id: 'q21_6', question: 'What is the Factory pattern?', questionKa: 'რა არის Factory შაბლონი?', options: ['A class that extends another', 'A function/method that creates and returns objects', 'A way to delete objects', 'A sorting algorithm'], optionsKa: ['კლასი რომელიც სხვას აფართოებს', 'ფუნქცია/მეთოდი, რომელიც ობიექტებს ქმნის და აბრუნებს', 'ობიექტების წაშლის გზა', 'სორტირების ალგორითმი'], correctIndex: 1, explanation: 'The Factory pattern uses a function or method to create objects, abstracting away the new keyword.', explanationKa: 'Factory შაბლონი ფუნქციას ან მეთოდს იყენებს ობიექტების შესაქმნელად, new საკვანძო სიტყვის აბსტრაჰირებით.' },
    { id: 'q21_7', question: 'What is separation of concerns in OOP?', questionKa: 'რა არის პასუხისმგებლობის გამიჯვნა OOP-ში?', options: ['Putting all code in one class', 'Each class handles one specific responsibility', 'Using only private fields', 'Avoiding inheritance'], optionsKa: ['ყველა კოდის ერთ კლასში მოთავსება', 'თითოეული კლასი ერთ კონკრეტულ პასუხისმგებლობას ასრულებს', 'მხოლოდ პრივატული ველების გამოყენება', 'მემკვიდრეობის თავიდან აცილება'], correctIndex: 1, explanation: 'Separation of concerns means each class should have a single, well-defined responsibility.', explanationKa: 'პასუხისმგებლობის გამიჯვნა ნიშნავს, რომ თითოეულ კლასს ერთი, კარგად განსაზღვრული პასუხისმგებლობა უნდა ჰქონდეს.' },
    { id: 'q21_8', question: 'How does method chaining work?', questionKa: 'როგორ მუშაობს მეთოდების ჯაჭვური შეკავშირება?', options: ['By using callbacks', 'By returning "this" from each method', 'By using async/await', 'By nesting functions'], optionsKa: ['callback-ების გამოყენებით', 'თითოეული მეთოდიდან "this"-ის დაბრუნებით', 'async/await-ის გამოყენებით', 'ფუნქციების ჩადგმით'], correctIndex: 1, explanation: 'Method chaining works by returning "this" from methods, allowing consecutive calls like obj.a().b().c().', explanationKa: 'მეთოდების ჯაჭვი მუშაობს მეთოდებიდან "this"-ის დაბრუნებით, რაც ზედიზედ გამოძახებას იძლევა: obj.a().b().c().' },
    { id: 'q21_9', question: 'What is the benefit of using private fields in a BankAccount class?', questionKa: 'რა სარგებელი აქვს BankAccount კლასში პრივატული ველების გამოყენებას?', options: ['Faster performance', 'Prevents direct access to the balance, enforcing validation', 'Reduces memory usage', 'Enables inheritance'], optionsKa: ['მეტი წარმადობა', 'ბალანსზე პირდაპირ წვდომას კრძალავს, ვალიდაციას აიძულებს', 'მეხსიერების მოხმარების შემცირება', 'მემკვიდრეობის საშუალება'], correctIndex: 1, explanation: 'Private fields like #balance prevent direct modification, forcing use of validated methods like deposit() and withdraw().', explanationKa: 'პრივატული ველები, როგორიცაა #balance, პირდაპირ მოდიფიკაციას კრძალავს, ვალიდირებული მეთოდების (deposit(), withdraw()) გამოყენებას აიძულებს.' },
    { id: 'q21_10', question: 'When should you prefer composition over inheritance?', questionKa: 'როდის უნდა ამჯობინოთ კომპოზიცია მემკვიდრეობას?', options: ['Always', 'When objects need shared behavior without being the same type', 'Never, inheritance is always better', 'Only for arrays'], optionsKa: ['ყოველთვის', 'როცა ობიექტებს საერთო ქცევა სჭირდებათ ერთი ტიპის გარეშე', 'არასოდეს, მემკვიდრეობა ყოველთვის უკეთესია', 'მხოლოდ მასივებისთვის'], correctIndex: 1, explanation: 'Composition is preferred when classes need to share behavior without a strict "is-a" relationship.', explanationKa: 'კომპოზიცია სასურველია როცა კლასებს ქცევის გაზიარება სჭირდებათ მკაცრი "არის-ა" ურთიერთობის გარეშე.' }
  ]
};

// Read the file
let content = fs.readFileSync('src/app/data/quizzes.ts', 'utf8');

// For each chapter, find the last question's closing brace and add new ones
for (const [chapterId, questions] of Object.entries(additionalQuestions)) {
  const lastQ = `q${chapterId}_5`;

  // Find the closing of the last question for this chapter
  const lastQIndex = content.indexOf(`id: '${lastQ}'`);
  if (lastQIndex === -1) {
    console.log(`Could not find ${lastQ}`);
    continue;
  }

  // Find the closing brace of this question (we need to find the right "}")
  let braceCount = 0;
  let i = content.indexOf('{', lastQIndex);
  let foundStart = false;
  for (; i < content.length; i++) {
    if (content[i] === '{') { braceCount++; foundStart = true; }
    if (content[i] === '}') { braceCount--; }
    if (foundStart && braceCount === 0) break;
  }

  // Build the new questions text
  let newQText = '';
  for (const q of questions) {
    newQText += `,\n      {\n`;
    newQText += `        id: '${q.id}',\n`;
    newQText += `        question: ${JSON.stringify(q.question)},\n`;
    newQText += `        questionKa: ${JSON.stringify(q.questionKa)},\n`;
    newQText += `        options: ${JSON.stringify(q.options)},\n`;
    newQText += `        optionsKa: ${JSON.stringify(q.optionsKa)},\n`;
    newQText += `        correctIndex: ${q.correctIndex},\n`;
    newQText += `        explanation: ${JSON.stringify(q.explanation)},\n`;
    newQText += `        explanationKa: ${JSON.stringify(q.explanationKa)}\n`;
    newQText += `      }`;
  }

  content = content.slice(0, i + 1) + newQText + content.slice(i + 1);
  console.log(`Added ${questions.length} questions for chapter ${chapterId}`);
}

fs.writeFileSync('src/app/data/quizzes.ts', content, 'utf8');
console.log('Done! All additional questions inserted.');
